version: '3.4'
services:
  jira-core:
    image: ragedunicorn/jira-core:1.0.1-stable
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    depends_on:
      - postgresql
    networks:
      - jira-core
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.jira-core.environment: "prod"
      com.ragedunicorn.jira-core.description: "JIRA Core"
  postgresql:
    image: ragedunicorn/postgresql:1.0.3-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - jira-core
    secrets:
      - com.ragedunicorn.postgresql.app_user
      - com.ragedunicorn.postgresql.app_user_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
networks:
  jira-core:
    driver: overlay
secrets:
  com.ragedunicorn.postgresql.app_user:
    external: true
  com.ragedunicorn.postgresql.app_user_password:
    external: true
