version: '3.7'
services:
  jira-core:
    build: .
    image: ragedunicorn/jira-core:${JIRA_TAG_VERSION}-dev
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    depends_on:
      - postgresql
    networks:
      - jira-core
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.jira-core.environment: "dev"
      com.ragedunicorn.jira-core.description: "JIRA Core"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - jira-core
    expose:
      - "5432"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.postgresql.environment: "dev"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
networks:
  jira-core:
    driver: bridge
