version: '3.7'
services:
  jira-core:
    build: .
    image: ragedunicorn/jira-core:${JIRA_TAG_VERSION}-stable
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      JIRA_DATABASE_NAME: "jira"
    depends_on:
      - postgresql
    networks:
      - jira-core
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.jira-core.environment: "prod"
      com.ragedunicorn.jira-core.description: "JIRA Core"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
    networks:
      - jira-core
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
networks:
  jira-core:
    driver: bridge
